/*
 Copyright (c) 2008 Yii Software LLC
 @license http://www.yiiframework.com/license/
 @author Qiang Xue <qiang.xue@gmail.com>
 @since 2.0
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,n,l){d instanceof String&&(d=String(d));for(var e=d.length,b=0;b<e;b++){var c=d[b];if(n.call(l,c,b,d))return{i:b,v:c}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,n,l){d!=Array.prototype&&d!=Object.prototype&&(d[n]=l.value)};
$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,n,l,e){if(n){l=$jscomp.global;d=d.split(".");for(e=0;e<d.length-1;e++){var b=d[e];b in l||(l[b]={});l=l[b]}d=d[d.length-1];e=l[d];n=n(e);n!=e&&null!=n&&$jscomp.defineProperty(l,d,{configurable:!0,writable:!0,value:n})}};
$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,l){return $jscomp.findInternal(this,d,l).v}},"es6","es3");
(function(d){d.fn.yiiActiveForm=function(b){return e[b]?e[b].apply(this,Array.prototype.slice.call(arguments,1)):"object"!==typeof b&&b?(d.error("Method "+b+" does not exist on jQuery.yiiActiveForm"),!1):e.init.apply(this,arguments)};var n={encodeErrorSummary:!0,errorSummary:".error-summary",validateOnSubmit:!0,errorCssClass:"has-error",successCssClass:"has-success",validatingCssClass:"validating",ajaxParam:"ajax",ajaxDataType:"json",validationUrl:void 0,ajaxSubmit:!1},l={id:void 0,name:void 0,container:void 0,
input:void 0,error:".help-block",encodeError:!0,validateOnChange:!0,validateOnBlur:!0,validateOnType:!1,validationDelay:500,enableAjaxValidation:!1,validate:void 0,status:0,cancelled:!1,value:void 0},e={init:function(a,m){return this.each(function(){var g=d(this);if(!g.data("yiiActiveForm")){var c=d.extend({},n,m||{});void 0===c.validationUrl&&(c.validationUrl=g.attr("action"));d.each(a,function(m){a[m]=d.extend({value:p(g,this)},l,this);b(g,a[m])});g.data("yiiActiveForm",{settings:c,attributes:a,
submitting:!1,validated:!1});g.bind("reset.yiiActiveForm",e.resetForm);c.validateOnSubmit&&(g.on("mouseup.yiiActiveForm keyup.yiiActiveForm",":submit",function(){g.data("yiiActiveForm").submitObject=d(this)}),g.on("submit.yiiActiveForm",e.submitForm))}})},add:function(a){var g=d(this);a=d.extend({value:p(g,a)},l,a);g.data("yiiActiveForm").attributes.push(a);b(g,a)},remove:function(b){var a=d(this),g=a.data("yiiActiveForm").attributes,c=-1,f=void 0;d.each(g,function(a){if(g[a].id==b)return c=a,f=g[a],
!1});0<=c&&(g.splice(c,1),q(a,f).off(".yiiActiveForm"));return f},validateAttribute:function(a){a=e.find.call(this,a);void 0!=a&&c(d(this),a,!0)},find:function(a){var b=d(this).data("yiiActiveForm").attributes,g=void 0;d.each(b,function(d){if(b[d].id==a)return g=b[d],!1});return g},destroy:function(){return this.each(function(){d(this).unbind(".yiiActiveForm");d(this).removeData("yiiActiveForm")})},data:function(){return this.data("yiiActiveForm")},validate:function(){var b=d(this),m=b.data("yiiActiveForm"),
c=!1,f={},e=a(),k=m.submitting;if(k){var l=d.Event("beforeValidate");b.trigger(l,[f,e]);if(!1===l.result){m.submitting=!1;return}}d.each(m.attributes,function(){this.cancelled=!1;if(m.submitting||2===this.status||3===this.status){var a=f[this.id];void 0===a&&(a=[],f[this.id]=a);var g=d.Event("beforeValidateAttribute");b.trigger(g,[this,a,e]);!1!==g.result?(this.validate&&this.validate(this,p(b,this),a,e,b),this.enableAjaxValidation&&(c=!0)):this.cancelled=!0}});d.when.apply(this,e).always(function(){for(var a in f)0===
f[a].length&&delete f[a];if(c){a=m.submitObject;var g="&"+m.settings.ajaxParam+"="+b.attr("id");a&&a.length&&a.attr("name")&&(g+="&"+a.attr("name")+"="+a.attr("value"));d.ajax({url:m.settings.validationUrl,type:b.attr("method"),data:b.serialize()+g,dataType:m.settings.ajaxDataType,headers:{"Ajax-Data-Type":m.settings.ajaxDataType},complete:function(a,g){b.trigger("ajaxComplete",[a,g])},beforeSend:function(a,g){b.trigger("ajaxBeforeSend",[a,g])},success:function(a){null!==a&&"object"===typeof a?(d.each(m.attributes,
function(){this.enableAjaxValidation&&!this.cancelled||delete a[this.id]}),h(b,d.extend(f,a),k)):h(b,f,k)},error:function(){m.submitting=!1}})}else m.submitting?setTimeout(function(){h(b,f,k)},200):h(b,f,k)})},submitForm:function(){var a=d(this),b=a.data("yiiActiveForm");if(b.validated){b.submitting=!1;var c=d.Event("beforeSubmit");a.trigger(c);return!1===c.result?b.validated=!1:!0}void 0!==b.settings.timer&&clearTimeout(b.settings.timer);b.submitting=!0;e.validate.call(a);return!1},resetForm:function(){var a=
d(this),b=a.data("yiiActiveForm");setTimeout(function(){d.each(b.attributes,function(){this.value=p(a,this);this.status=0;var d=a.find(this.container);d.removeClass(b.settings.validatingCssClass+" "+b.settings.errorCssClass+" "+b.settings.successCssClass);d.find(this.error).html("")});a.find(b.settings.errorSummary).hide().find("ul").html("")},1)}},b=function(a,b){var g=q(a,b);if(b.validateOnChange)g.on("change.yiiActiveForm",function(){c(a,b,!1)});if(b.validateOnBlur)g.on("blur.yiiActiveForm",function(){0!=
b.status&&1!=b.status||c(a,b,!b.status)});if(b.validateOnType)g.on("keyup.yiiActiveForm",function(g){-1===d.inArray(g.which,[16,17,18,37,38,39,40])&&b.value!==p(a,b)&&c(a,b,!1,b.validationDelay)})},c=function(a,b,c,f){var g=a.data("yiiActiveForm");c&&(b.status=2);d.each(g.attributes,function(){this.value!==p(a,this)&&(this.status=2,c=!0)});c&&(void 0!==g.settings.timer&&clearTimeout(g.settings.timer),g.settings.timer=setTimeout(function(){g.submitting||a.is(":hidden")||(d.each(g.attributes,function(){2===
this.status&&(this.status=3,a.find(this.container).addClass(g.settings.validatingCssClass))}),e.validate.call(a))},f?f:200))},a=function(){var a=[];a.add=function(a){this.push(new d.Deferred(a))};return a},h=function(a,b,c){var g=a.data("yiiActiveForm");if(c){var e=[];d.each(g.attributes,function(){!this.cancelled&&f(a,this,b)&&e.push(this.input)});a.trigger("afterValidate",[b]);k(a,b);if(e.length){c=a.find(e.join(",")).first().closest(":visible").offset().top;var h=d(window).scrollTop();(c<h||c>
h+d(window).height)&&d(window).scrollTop(c);g.submitting=!1}else g.validated=!0,c=g.submitObject||a.find(":submit:first"),c.length&&"submit"==c.attr("type")&&c.attr("name")&&(h=d('input[type="hidden"][name="'+c.attr("name")+'"]',a),h.length?h.attr("value",c.attr("value")):d("<input>").attr({type:"hidden",name:c.attr("name"),value:c.attr("value")}).appendTo(a)),g.settings.ajaxSubmit?(c={"Ajax-Data-Type":g.settings.ajaxDataType},d.ajax({url:a.attr("action"),type:a.attr("method"),data:a.serialize(),
dataType:g.settings.ajaxDataType,headers:c,complete:function(b,c){a.trigger("ajaxSubmitComplete",[b,c])},beforeSend:function(b,c){a.trigger("beforeAjaxSubmit",[b,c])},success:function(b){a.trigger("ajaxSubmitSuccess",[b])},error:function(){a.trigger("ajaxSubmitError",[])}})):a.submit()}else d.each(g.attributes,function(){this.cancelled||2!==this.status&&3!==this.status||f(a,this,b)})},f=function(a,b,c){var f=a.data("yiiActiveForm"),g=q(a,b),e=!1;d.isArray(c[b.id])||(c[b.id]=[]);a.trigger("afterValidateAttribute",
[b,c[b.id]]);b.status=1;if(g.length){e=0<c[b.id].length;g=a.find(b.container);var h=g.find(b.error);e?(b.encodeError?h.text(c[b.id][0]):h.html(c[b.id][0]),g.removeClass(f.settings.validatingCssClass+" "+f.settings.successCssClass).addClass(f.settings.errorCssClass)):(h.empty(),g.removeClass(f.settings.validatingCssClass+" "+f.settings.errorCssClass+" ").addClass(f.settings.successCssClass));b.value=p(a,b)}return e},k=function(a,b){var c=a.data("yiiActiveForm");a=a.find(c.settings.errorSummary);var f=
a.find("ul").empty();a.length&&b&&(d.each(c.attributes,function(){if(d.isArray(b[this.id])&&b[this.id].length){var a=d("<li/>");c.settings.encodeErrorSummary?a.text(b[this.id][0]):a.html(b[this.id][0]);f.append(a)}}),a.toggle(0<f.find("li").length))},p=function(a,b){b=q(a,b);var c=b.attr("type");return"checkbox"===c||"radio"===c?(c=b.filter(":checked"),c.length||(c=a.find('input[type=hidden][name="'+b.attr("name")+'"]')),c.val()):b.val()},q=function(a,b){a=a.find(b.input);return a.length&&"div"===
a[0].tagName.toLowerCase()?a.find("input"):a}})(window.jQuery);
yii.validation=function(d){function n(b,c,a){if("undefined"===typeof File)return[];b=d(b.input,b.$form).get(0).files;return b?0===b.length?(a.skipOnEmpty||c.push(a.uploadRequired),[]):a.maxFiles&&a.maxFiles<b.length?(c.push(a.tooMany),[]):b:(c.push(a.message),[])}function l(b,c,a){if(a.extensions&&0<a.extensions.length){var d=b.name.lastIndexOf(".");d=~d?b.name.substr(d+1,b.name.length).toLowerCase():"";~a.extensions.indexOf(d)||c.push(a.wrongExtension.replace(/\{file\}/g,b.name))}if(a.mimeTypes&&
0<a.mimeTypes.length){a:{d=a.mimeTypes;for(var f=b.type,e=0,l=d.length;e<l;e++)if((new RegExp(d[e])).test(f)){d=!0;break a}d=!1}d||c.push(a.wrongMimeType.replace(/\{file\}/g,b.name))}a.maxSize&&a.maxSize<b.size&&c.push(a.tooBig.replace(/\{file\}/g,b.name));a.minSize&&a.minSize>b.size&&c.push(a.tooSmall.replace(/\{file\}/g,b.name))}var e={isEmpty:function(b){return null===b||void 0===b||d.isArray(b)&&0===b.length||""===b},addMessage:function(b,c,a){b.push(c.replace(/\{value\}/g,a))},required:function(b,
c,a){var h=!1;if(void 0===a.requiredValue){var f="string"==typeof b||b instanceof String;if(a.strict&&void 0!==b||!a.strict&&!e.isEmpty(f?d.trim(b):b))h=!0}else if(!a.strict&&b==a.requiredValue||a.strict&&b===a.requiredValue)h=!0;h||e.addMessage(c,a.message,b)},"boolean":function(b,c,a){a.skipOnEmpty&&e.isEmpty(b)||(a.strict||b!=a.trueValue&&b!=a.falseValue)&&(!a.strict||b!==a.trueValue&&b!==a.falseValue)&&e.addMessage(c,a.message,b)},string:function(b,c,a){a.skipOnEmpty&&e.isEmpty(b)||("string"!==
typeof b?e.addMessage(c,a.message,b):void 0!==a.is&&b.length!=a.is?e.addMessage(c,a.notEqual,b):(void 0!==a.min&&b.length<a.min&&e.addMessage(c,a.tooShort,b),void 0!==a.max&&b.length>a.max&&e.addMessage(c,a.tooLong,b)))},file:function(b,c,a){b=n(b,c,a);d.each(b,function(b,d){l(d,c,a)})},image:function(b,c,a,h){b=n(b,c,a);d.each(b,function(b,k){l(k,c,a);"undefined"!==typeof FileReader&&(b=d.Deferred(),e.validateImage(k,c,a,b,new FileReader,new Image),h.push(b))})},validateImage:function(b,c,a,d,f,
e){e.onload=function(){a.minWidth&&e.width<a.minWidth&&c.push(a.underWidth.replace(/\{file\}/g,b.name));a.maxWidth&&e.width>a.maxWidth&&c.push(a.overWidth.replace(/\{file\}/g,b.name));a.minHeight&&e.height<a.minHeight&&c.push(a.underHeight.replace(/\{file\}/g,b.name));a.maxHeight&&e.height>a.maxHeight&&c.push(a.overHeight.replace(/\{file\}/g,b.name));d.resolve()};e.onerror=function(){c.push(a.notImage.replace(/\{file\}/g,b.name));d.resolve()};f.onload=function(){e.src=this.result};f.onerror=function(){d.resolve()};
f.readAsDataURL(b)},number:function(b,c,a){a.skipOnEmpty&&e.isEmpty(b)||("string"!==typeof b||a.pattern.test(b)?(void 0!==a.min&&b<a.min&&e.addMessage(c,a.tooSmall,b),void 0!==a.max&&b>a.max&&e.addMessage(c,a.tooBig,b)):e.addMessage(c,a.message,b))},range:function(b,c,a){if(!a.skipOnEmpty||!e.isEmpty(b))if(!a.allowArray&&d.isArray(b))e.addMessage(c,a.message,b);else{var h=!0;d.each(d.isArray(b)?b:[b],function(b,c){return-1==d.inArray(c,a.range)?h=!1:!0});void 0===a.not&&(a.not=!1);a.not===h&&e.addMessage(c,
a.message,b)}},regularExpression:function(b,c,a){a.skipOnEmpty&&e.isEmpty(b)||(!a.not&&!a.pattern.test(b)||a.not&&a.pattern.test(b))&&e.addMessage(c,a.message,b)},email:function(b,c,a){if(!a.skipOnEmpty||!e.isEmpty(b)){var d=/^((?:"?([^"]*)"?\s)?)(?:\s+)?(?:(<?)((.+)@([^>]+))(>?))$/.exec(b);if(null===d)d=!1;else{var f=d[5],k=d[6];a.enableIDN&&(f=punycode.toASCII(f),k=punycode.toASCII(k),b=d[1]+d[3]+f+"@"+k+d[7]);d=64<f.length?!1:254<(f+"@"+k).length?!1:a.pattern.test(b)||a.allowName&&a.fullPattern.test(b)}d||
e.addMessage(c,a.message,b)}},url:function(b,c,a){if(!a.skipOnEmpty||!e.isEmpty(b)){a.defaultScheme&&!/:\/\//.test(b)&&(b=a.defaultScheme+"://"+b);var d=!0;if(a.enableIDN){var f=/^([^:]+):\/\/([^\/]+)(.*)$/.exec(b);null===f?d=!1:b=f[1]+"://"+punycode.toASCII(f[2])+f[3]}d&&a.pattern.test(b)||e.addMessage(c,a.message,b)}},trim:function(b,c,a){b=b.find(c.input);c=b.val();a.skipOnEmpty&&e.isEmpty(c)||(c=d.trim(c),b.val(c));return c},captcha:function(b,c,a){if(!a.skipOnEmpty||!e.isEmpty(b)){var h=d("body").data(a.hashKey);
h=null==h?a.hash:h[a.caseSensitive?0:1];for(var f=a.caseSensitive?b:b.toLowerCase(),k=f.length-1,l=0;0<=k;--k)l+=f.charCodeAt(k);l!=h&&e.addMessage(c,a.message,b)}},compare:function(b,c,a,h){if(!a.skipOnEmpty||!e.isEmpty(b)){if(void 0===a.compareAttribute)var f=a.compareValue;else{h=h.data("yiiActiveForm").attributes;for(var k=h.length-1;0<=k;k--)h[k].id===a.compareAttribute&&(f=d(h[k].input).val())}"number"===a.type&&(b=parseFloat(b),f=parseFloat(f));switch(a.operator){case "==":f=b==f;break;case "===":f=
b===f;break;case "!=":f=b!=f;break;case "!==":f=b!==f;break;case ">":f=b>f;break;case ">=":f=b>=f;break;case "<":f=b<f;break;case "<=":f=b<=f;break;default:f=!1}f||e.addMessage(c,a.message,b)}},ip:function(b,c,a){if(!a.skipOnEmpty||!e.isEmpty(b)){var d=null,f=null,k=(new RegExp(a.ipParsePattern)).exec(b);k&&(d=k[1]||null,b=k[2],f=k[4]||null);!0===a.subnet&&null===f?e.addMessage(c,a.messages.noSubnet,b):!1===a.subnet&&null!==f?e.addMessage(c,a.messages.hasSubnet,b):!1===a.negation&&null!==d?e.addMessage(c,
a.messages.message,b):6==(-1===b.indexOf(":")?4:6)?((new RegExp(a.ipv6Pattern)).test(b)||e.addMessage(c,a.messages.message,b),a.ipv6||e.addMessage(c,a.messages.ipv6NotAllowed,b)):((new RegExp(a.ipv4Pattern)).test(b)||e.addMessage(c,a.messages.message,b),a.ipv4||e.addMessage(c,a.messages.ipv4NotAllowed,b))}}};return e}(jQuery);
