/*
 Copyright (c) 2008 Yii Software LLC
 @license http://www.yiiframework.com/license/
 @author Qiang Xue <qiang.xue@gmail.com>
 @since 2.0
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,l,k){d instanceof String&&(d=String(d));for(var e=d.length,a=0;a<e;a++){var c=d[a];if(l.call(k,c,a,d))return{i:a,v:c}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,l,k){d!=Array.prototype&&d!=Object.prototype&&(d[l]=k.value)};
$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,l,k,e){if(l){k=$jscomp.global;d=d.split(".");for(e=0;e<d.length-1;e++){var a=d[e];a in k||(k[a]={});k=k[a]}d=d[d.length-1];e=k[d];l=l(e);l!=e&&null!=l&&$jscomp.defineProperty(k,d,{configurable:!0,writable:!0,value:l})}};
$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,k){return $jscomp.findInternal(this,d,k).v}},"es6","es3");
yii.validation=function(d){function l(a,c,b){if("undefined"===typeof File)return[];a=d(a.input,a.$form).get(0).files;return a?0===a.length?(b.skipOnEmpty||c.push(b.uploadRequired),[]):b.maxFiles&&b.maxFiles<a.length?(c.push(b.tooMany),[]):a:(c.push(b.message),[])}function k(a,c,b){if(b.extensions&&0<b.extensions.length){var g=a.name.lastIndexOf(".");g=~g?a.name.substr(g+1,a.name.length).toLowerCase():"";~b.extensions.indexOf(g)||c.push(b.wrongExtension.replace(/\{file\}/g,a.name))}if(b.mimeTypes&&
0<b.mimeTypes.length){a:{g=b.mimeTypes;for(var f=a.type,e=0,d=g.length;e<d;e++)if((new RegExp(g[e])).test(f)){g=!0;break a}g=!1}g||c.push(b.wrongMimeType.replace(/\{file\}/g,a.name))}b.maxSize&&b.maxSize<a.size&&c.push(b.tooBig.replace(/\{file\}/g,a.name));b.minSize&&b.minSize>a.size&&c.push(b.tooSmall.replace(/\{file\}/g,a.name))}var e={isEmpty:function(a){return null===a||void 0===a||d.isArray(a)&&0===a.length||""===a},addMessage:function(a,c,b){a.push(c.replace(/\{value\}/g,b))},required:function(a,
c,b){var g=!1;if(void 0===b.requiredValue){var f="string"==typeof a||a instanceof String;if(b.strict&&void 0!==a||!b.strict&&!e.isEmpty(f?d.trim(a):a))g=!0}else if(!b.strict&&a==b.requiredValue||b.strict&&a===b.requiredValue)g=!0;g||e.addMessage(c,b.message,a)},"boolean":function(a,c,b){b.skipOnEmpty&&e.isEmpty(a)||(b.strict||a!=b.trueValue&&a!=b.falseValue)&&(!b.strict||a!==b.trueValue&&a!==b.falseValue)&&e.addMessage(c,b.message,a)},string:function(a,c,b){b.skipOnEmpty&&e.isEmpty(a)||("string"!==
typeof a?e.addMessage(c,b.message,a):void 0!==b.is&&a.length!=b.is?e.addMessage(c,b.notEqual,a):(void 0!==b.min&&a.length<b.min&&e.addMessage(c,b.tooShort,a),void 0!==b.max&&a.length>b.max&&e.addMessage(c,b.tooLong,a)))},file:function(a,c,b){a=l(a,c,b);d.each(a,function(a,f){k(f,c,b)})},image:function(a,c,b,g){a=l(a,c,b);d.each(a,function(a,h){k(h,c,b);"undefined"!==typeof FileReader&&(a=d.Deferred(),e.validateImage(h,c,b,a,new FileReader,new Image),g.push(a))})},validateImage:function(a,c,b,e,f,
d){d.onload=function(){b.minWidth&&d.width<b.minWidth&&c.push(b.underWidth.replace(/\{file\}/g,a.name));b.maxWidth&&d.width>b.maxWidth&&c.push(b.overWidth.replace(/\{file\}/g,a.name));b.minHeight&&d.height<b.minHeight&&c.push(b.underHeight.replace(/\{file\}/g,a.name));b.maxHeight&&d.height>b.maxHeight&&c.push(b.overHeight.replace(/\{file\}/g,a.name));e.resolve()};d.onerror=function(){c.push(b.notImage.replace(/\{file\}/g,a.name));e.resolve()};f.onload=function(){d.src=this.result};f.onerror=function(){e.resolve()};
f.readAsDataURL(a)},number:function(a,c,b){b.skipOnEmpty&&e.isEmpty(a)||("string"!==typeof a||b.pattern.test(a)?(void 0!==b.min&&a<b.min&&e.addMessage(c,b.tooSmall,a),void 0!==b.max&&a>b.max&&e.addMessage(c,b.tooBig,a)):e.addMessage(c,b.message,a))},range:function(a,c,b){if(!b.skipOnEmpty||!e.isEmpty(a))if(!b.allowArray&&d.isArray(a))e.addMessage(c,b.message,a);else{var g=!0;d.each(d.isArray(a)?a:[a],function(a,c){return-1==d.inArray(c,b.range)?g=!1:!0});void 0===b.not&&(b.not=!1);b.not===g&&e.addMessage(c,
b.message,a)}},regularExpression:function(a,c,b){b.skipOnEmpty&&e.isEmpty(a)||(!b.not&&!b.pattern.test(a)||b.not&&b.pattern.test(a))&&e.addMessage(c,b.message,a)},email:function(a,c,b){if(!b.skipOnEmpty||!e.isEmpty(a)){var d=/^((?:"?([^"]*)"?\s)?)(?:\s+)?(?:(<?)((.+)@([^>]+))(>?))$/.exec(a);if(null===d)d=!1;else{var f=d[5],h=d[6];b.enableIDN&&(f=punycode.toASCII(f),h=punycode.toASCII(h),a=d[1]+d[3]+f+"@"+h+d[7]);d=64<f.length?!1:254<(f+"@"+h).length?!1:b.pattern.test(a)||b.allowName&&b.fullPattern.test(a)}d||
e.addMessage(c,b.message,a)}},url:function(a,c,b){if(!b.skipOnEmpty||!e.isEmpty(a)){b.defaultScheme&&!/:\/\//.test(a)&&(a=b.defaultScheme+"://"+a);var d=!0;if(b.enableIDN){var f=/^([^:]+):\/\/([^\/]+)(.*)$/.exec(a);null===f?d=!1:a=f[1]+"://"+punycode.toASCII(f[2])+f[3]}d&&b.pattern.test(a)||e.addMessage(c,b.message,a)}},trim:function(a,c,b){a=a.find(c.input);c=a.val();b.skipOnEmpty&&e.isEmpty(c)||(c=d.trim(c),a.val(c));return c},captcha:function(a,c,b){if(!b.skipOnEmpty||!e.isEmpty(a)){var g=d("body").data(b.hashKey);
g=null==g?b.hash:g[b.caseSensitive?0:1];for(var f=b.caseSensitive?a:a.toLowerCase(),h=f.length-1,k=0;0<=h;--h)k+=f.charCodeAt(h);k!=g&&e.addMessage(c,b.message,a)}},compare:function(a,c,b,g){if(!b.skipOnEmpty||!e.isEmpty(a)){if(void 0===b.compareAttribute)var f=b.compareValue;else{g=g.data("yiiActiveForm").attributes;for(var h=g.length-1;0<=h;h--)g[h].id===b.compareAttribute&&(f=d(g[h].input).val())}"number"===b.type&&(a=parseFloat(a),f=parseFloat(f));switch(b.operator){case "==":f=a==f;break;case "===":f=
a===f;break;case "!=":f=a!=f;break;case "!==":f=a!==f;break;case ">":f=a>f;break;case ">=":f=a>=f;break;case "<":f=a<f;break;case "<=":f=a<=f;break;default:f=!1}f||e.addMessage(c,b.message,a)}},ip:function(a,c,b){if(!b.skipOnEmpty||!e.isEmpty(a)){var d=null,f=null,h=(new RegExp(b.ipParsePattern)).exec(a);h&&(d=h[1]||null,a=h[2],f=h[4]||null);!0===b.subnet&&null===f?e.addMessage(c,b.messages.noSubnet,a):!1===b.subnet&&null!==f?e.addMessage(c,b.messages.hasSubnet,a):!1===b.negation&&null!==d?e.addMessage(c,
b.messages.message,a):6==(-1===a.indexOf(":")?4:6)?((new RegExp(b.ipv6Pattern)).test(a)||e.addMessage(c,b.messages.message,a),b.ipv6||e.addMessage(c,b.messages.ipv6NotAllowed,a)):((new RegExp(b.ipv4Pattern)).test(a)||e.addMessage(c,b.messages.message,a),b.ipv4||e.addMessage(c,b.messages.ipv4NotAllowed,a))}}};return e}(jQuery);
